//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CollegeMgntSystemEntities1 : DbContext
    {
        public CollegeMgntSystemEntities1()
            : base("name=CollegeMgntSystemEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<staff_designations> staff_designations { get; set; }
        public virtual DbSet<staff_info> staff_info { get; set; }
        public virtual DbSet<student_batches> student_batches { get; set; }
        public virtual DbSet<students_info> students_info { get; set; }
    
        public virtual ObjectResult<USP_AddStaffDetails_Result> USP_AddStaffDetails(Nullable<System.DateTime> join_date, Nullable<int> designnation, string first_name, string middle_name, string last_name, string gender, string mobile_1, string moible_2, string email, string qualification)
        {
            var join_dateParameter = join_date.HasValue ?
                new ObjectParameter("join_date", join_date) :
                new ObjectParameter("join_date", typeof(System.DateTime));
    
            var designnationParameter = designnation.HasValue ?
                new ObjectParameter("designnation", designnation) :
                new ObjectParameter("designnation", typeof(int));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var mobile_1Parameter = mobile_1 != null ?
                new ObjectParameter("mobile_1", mobile_1) :
                new ObjectParameter("mobile_1", typeof(string));
    
            var moible_2Parameter = moible_2 != null ?
                new ObjectParameter("moible_2", moible_2) :
                new ObjectParameter("moible_2", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("qualification", qualification) :
                new ObjectParameter("qualification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_AddStaffDetails_Result>("USP_AddStaffDetails", join_dateParameter, designnationParameter, first_nameParameter, middle_nameParameter, last_nameParameter, genderParameter, mobile_1Parameter, moible_2Parameter, emailParameter, qualificationParameter);
        }
    
        public virtual ObjectResult<USP_AddStudentsDetails_Result> USP_AddStudentsDetails(string reg_no, string first_name, string last_name, Nullable<System.DateTime> date_of_birth, string gender, Nullable<int> faculty, Nullable<int> academic_status, Nullable<int> batch, string blood_group, string email, Nullable<int> student_status)
        {
            var reg_noParameter = reg_no != null ?
                new ObjectParameter("reg_no", reg_no) :
                new ObjectParameter("reg_no", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var date_of_birthParameter = date_of_birth.HasValue ?
                new ObjectParameter("date_of_birth", date_of_birth) :
                new ObjectParameter("date_of_birth", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var facultyParameter = faculty.HasValue ?
                new ObjectParameter("faculty", faculty) :
                new ObjectParameter("faculty", typeof(int));
    
            var academic_statusParameter = academic_status.HasValue ?
                new ObjectParameter("academic_status", academic_status) :
                new ObjectParameter("academic_status", typeof(int));
    
            var batchParameter = batch.HasValue ?
                new ObjectParameter("batch", batch) :
                new ObjectParameter("batch", typeof(int));
    
            var blood_groupParameter = blood_group != null ?
                new ObjectParameter("blood_group", blood_group) :
                new ObjectParameter("blood_group", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var student_statusParameter = student_status.HasValue ?
                new ObjectParameter("student_status", student_status) :
                new ObjectParameter("student_status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_AddStudentsDetails_Result>("USP_AddStudentsDetails", reg_noParameter, first_nameParameter, last_nameParameter, date_of_birthParameter, genderParameter, facultyParameter, academic_statusParameter, batchParameter, blood_groupParameter, emailParameter, student_statusParameter);
        }
    
        public virtual ObjectResult<USP_DeleteStaffDetails_Result> USP_DeleteStaffDetails(Nullable<int> staff_id)
        {
            var staff_idParameter = staff_id.HasValue ?
                new ObjectParameter("staff_id", staff_id) :
                new ObjectParameter("staff_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DeleteStaffDetails_Result>("USP_DeleteStaffDetails", staff_idParameter);
        }
    
        public virtual ObjectResult<USP_DeleteStudentsDetails_Result> USP_DeleteStudentsDetails(Nullable<int> student_id)
        {
            var student_idParameter = student_id.HasValue ?
                new ObjectParameter("student_id", student_id) :
                new ObjectParameter("student_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_DeleteStudentsDetails_Result>("USP_DeleteStudentsDetails", student_idParameter);
        }
    
        public virtual ObjectResult<USP_GetStaffDetailss_Result> USP_GetStaffDetailss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetStaffDetailss_Result>("USP_GetStaffDetailss");
        }
    
        public virtual ObjectResult<USP_GetStudensDetailss_Result> USP_GetStudensDetailss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetStudensDetailss_Result>("USP_GetStudensDetailss");
        }
    
        public virtual ObjectResult<USP_UpdateStaffDetailss_Result> USP_UpdateStaffDetailss(Nullable<int> staff_id, Nullable<System.DateTime> join_date, Nullable<int> designnation, string first_name, string middle_name, string last_name, string gender, string mobile_1, string moible_2, string email, string qualification)
        {
            var staff_idParameter = staff_id.HasValue ?
                new ObjectParameter("staff_id", staff_id) :
                new ObjectParameter("staff_id", typeof(int));
    
            var join_dateParameter = join_date.HasValue ?
                new ObjectParameter("join_date", join_date) :
                new ObjectParameter("join_date", typeof(System.DateTime));
    
            var designnationParameter = designnation.HasValue ?
                new ObjectParameter("designnation", designnation) :
                new ObjectParameter("designnation", typeof(int));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var mobile_1Parameter = mobile_1 != null ?
                new ObjectParameter("mobile_1", mobile_1) :
                new ObjectParameter("mobile_1", typeof(string));
    
            var moible_2Parameter = moible_2 != null ?
                new ObjectParameter("moible_2", moible_2) :
                new ObjectParameter("moible_2", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("qualification", qualification) :
                new ObjectParameter("qualification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_UpdateStaffDetailss_Result>("USP_UpdateStaffDetailss", staff_idParameter, join_dateParameter, designnationParameter, first_nameParameter, middle_nameParameter, last_nameParameter, genderParameter, mobile_1Parameter, moible_2Parameter, emailParameter, qualificationParameter);
        }
    
        public virtual ObjectResult<USP_UpdateStudentsDetailss_Result> USP_UpdateStudentsDetailss(Nullable<int> student_id, string reg_no, string first_name, string last_name, Nullable<System.DateTime> date_of_birth, string gender, Nullable<int> faculty, Nullable<int> academic_status, Nullable<int> batch, string blood_group, string email, Nullable<int> student_status)
        {
            var student_idParameter = student_id.HasValue ?
                new ObjectParameter("student_id", student_id) :
                new ObjectParameter("student_id", typeof(int));
    
            var reg_noParameter = reg_no != null ?
                new ObjectParameter("reg_no", reg_no) :
                new ObjectParameter("reg_no", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var date_of_birthParameter = date_of_birth.HasValue ?
                new ObjectParameter("date_of_birth", date_of_birth) :
                new ObjectParameter("date_of_birth", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var facultyParameter = faculty.HasValue ?
                new ObjectParameter("faculty", faculty) :
                new ObjectParameter("faculty", typeof(int));
    
            var academic_statusParameter = academic_status.HasValue ?
                new ObjectParameter("academic_status", academic_status) :
                new ObjectParameter("academic_status", typeof(int));
    
            var batchParameter = batch.HasValue ?
                new ObjectParameter("batch", batch) :
                new ObjectParameter("batch", typeof(int));
    
            var blood_groupParameter = blood_group != null ?
                new ObjectParameter("blood_group", blood_group) :
                new ObjectParameter("blood_group", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var student_statusParameter = student_status.HasValue ?
                new ObjectParameter("student_status", student_status) :
                new ObjectParameter("student_status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_UpdateStudentsDetailss_Result>("USP_UpdateStudentsDetailss", student_idParameter, reg_noParameter, first_nameParameter, last_nameParameter, date_of_birthParameter, genderParameter, facultyParameter, academic_statusParameter, batchParameter, blood_groupParameter, emailParameter, student_statusParameter);
        }
    }
}
