//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff_info()
        {
            this.students_info = new HashSet<students_info>();
        }
    
        public int staff_id { get; set; }
        public System.DateTime join_date { get; set; }
        public Nullable<int> designation { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string mobile_1 { get; set; }
        public string mobile_2 { get; set; }
        public string email { get; set; }
        public string qualification { get; set; }
    
        public virtual staff_designations staff_designations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<students_info> students_info { get; set; }
    }
}
